Fix EntityPlayer/nextContainerCounter signature change
Causes method '()V iq/ch' to not be reobfuscated, crashing EnderStorage

https://gist.github.com/4264901

 Encountered an unexpected exception NoSuchMethodError
 java.lang.NoSuchMethodError: iq.ch()V
    at codechicken.core.ServerUtils.openSMPContainer(ServerUtils.java:154)