MCPC/CPCM compatibility
This allows both MCPC and CPCM to be built from the same source.

Squashed commit of the following:

commit f4595d62ac23eeec6042aa36cdb59fd2da6872f0
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 14:13:28 2012 -0800

    Add _CB to BCD API methods

commit 1c7b6ac4cde414e8abbc7554e5f3b0027a7b1b50
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 14:04:47 2012 -0800

    Revert externalToolBuilder script change to reduce sizeof MCPC/CPCM diff

commit a90e1e8a22a5bd0e2326ac8af5a3f14866542a36
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 13:57:43 2012 -0800

    Remove CPCM ChangeLog from git to reduce size of MCPC diff

    Now available on wiki at https://github.com/agaricusb/MCPC-1.4.5/wiki/ChangeLog

commit db2ec851cc2f1ac20276bfb24c9eeb3980d157fb
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 13:41:21 2012 -0800

    Detect MCPC/CPCM from reobfuscation

commit d7831e19bab37ab5c8d9e483893cf6615c62e1f6
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 12:46:51 2012 -0800

    Reduce size of MCPC/CPCM diff

commit f49b2f30a8f5ba54ac4e2e6d0b3b0af48f30d6fe
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 12:17:26 2012 -0800

    Add CB classes to fml_marker interfaces, so MCPC can build from same source as CPCM

commit 4a9aaece449b6c45cbcba4c56a627d76b1b74278
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 11:49:34 2012 -0800

    Add quick-and-dirty reobfuscate script

    Bump build number to 006

commit e89415d9c25c9c940021d68185f4a4e3c8ac561b
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 11:07:52 2012 -0800

    Enable Block setTextureFile on server for https://github.com/agaricusb/MCPC-1.4.5/issues/4 Secret Rooms Mod, many others: cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: [Block subclass].setTextureFile

commit bde31ba88f00fbd9e83f415e891d52767f512b1c
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 11:05:08 2012 -0800

    Compile against ModLoader as a binary

commit 6b56aa624a536bf47ed120a689ebee8cd41225c2
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 11:04:56 2012 -0800

    Add lib/trove-3.0.3.jar to classpath

commit 0cf8832b00909ea90f884518e46851b8b610e0d2
Merge: 7b2d315 9f13b6c
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 10:54:39 2012 -0800

    Update to MCPC dev 3.1 with Forge #430

    Merge branch 'master' into cpcm

    Conflicts:
    	src/net/minecraft/server/Block.java

commit 7b2d31568e37b292065cfd7d174366a2dc146941
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 00:29:31 2012 -0800

    Add ModLoader class - Secret Rooms Mod now works\!

commit 9abef6b50d801ef4ce289975093126bbe6d63cb7
Author: Agaricus <agaricusb@yahoo.com>
Date:   Sat Dec 15 00:04:15 2012 -0800

    Fix Block setTextureFile signature. Fixes https://github.com/agaricusb/MCPC-1.4.5/issues/4 Secret Rooms Mod, many others: cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: [Block subclass].setTextureFile

commit 08991eebc8568722de44ea5b02afbe05e3716517
Author: Agaricus <agaricusb@yahoo.com>
Date:   Wed Dec 12 20:56:45 2012 -0800

    Update change log

commit 47b8312338400884d1ab4eb23ccd72ce86673e44
Author: Agaricus <agaricusb@yahoo.com>
Date:   Wed Dec 12 20:41:55 2012 -0800

    Add missing trove4j

commit 3b894b2953b5700f34f8ad9fa87b81cf88f5b898
Merge: 08f5db4 376c3c7
Author: Agaricus <agaricusb@yahoo.com>
Date:   Wed Dec 12 20:20:04 2012 -0800

    Merge branch 'master' of https://github.com/bloodmc/MCPC-1.4.5 into cpcm

    This updates to MCPC mcpc-spigot-1.4.5-b1.0.jar with Spigot #290

    Conflicts:
    	src/org/bukkit/craftbukkit/CraftServer.java

commit 08f5db4e9e00e583bf8340c05932a188ab20e6e1
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 20:50:02 2012 -0800

    Fix EntityPlayer/nextContainerCounter signature change

    Causes method '()V iq/ch' to not be reobfuscated, crashing EnderStorage

    https://gist.github.com/4264901

     Encountered an unexpected exception NoSuchMethodError
     java.lang.NoSuchMethodError: iq.ch()V
        at codechicken.core.ServerUtils.openSMPContainer(ServerUtils.java:154)

commit 6d217d19a0903b6a5e5fd4816b925705149eea84
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 19:44:05 2012 -0800

    Add CPCM ChangeLog

commit 65a62a58203db7a8eaee567b4e35dd89be574654
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 19:37:25 2012 -0800

    Update server brand

commit a005b51387919603661022f8bafe9237da29df71
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 19:24:47 2012 -0800

    Fix BlockChangeDelegate interface in World. This now runs, and you can connect.

commit 04b177b4a40daa5ccb7f30b8d4dabc3ce8487d66
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 19:12:31 2012 -0800

    Fix getBiome use in getBiomeGenForCoordsBody

commit 614ce307ee610bd9ff83052c29ba81b0a8606f77
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 19:03:28 2012 -0800

    Fix WorldChunkManager duplicate method after reobf getBiome -> a

commit bdb6087710e1c801a622b94716edffaf06f9041b
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 18:57:24 2012 -0800

    Copy cb2obf.srg from https://github.com/agaricusb/MinecraftRemapping/blob/master/cb2obf.srg

commit e12cafd26467060719c02d8ffcd9ad36a2342ea8
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 18:45:29 2012 -0800

    Revert "Disable FML class transformers for testing"

    This reverts commit c400882015aa4041d2ccf38e52c6439f69141ce5.

commit c400882015aa4041d2ccf38e52c6439f69141ce5
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 18:44:33 2012 -0800

    Disable FML class transformers for testing

    Still crashes with same java.lang.ClassFormatError: Duplicate method name&signature in class file yw
    https://gist.github.com/4264411

commit fabe5f1e00b14e732ddd38749c7d482e08a0ab6d
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 18:03:52 2012 -0800

    Remove static interfaces on Block and EntityHuman, allow FML to add dynamically

    Fixes: java.lang.ClassFormatError: Duplicate interface name in class file amj
    (full trace at https://gist.github.com/4260365)
    but fml_marker.cfg adds it, too. This error only occurs on remapped cb2obf
    since the fml_marker.cfg specifies obf and MCP mappings, but not CB, so
    the dynamic interface addition wasn't functional in MCPC.

commit 0d2922fad324cfd926dde3baa15937e9947471f3
Author: Agaricus <agaricusb@yahoo.com>
Date:   Tue Dec 11 17:40:31 2012 -0800

    Update compile jar tool